dist: xenial

sudo: required

language: python

python:
  - "3.7"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

install:
  - pwd
  - curl -Ls http://cloudmesh.github.io/get | sh
  - mkdir -p ~/.cloudmesh
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-common/master/cloudmesh/etc/cloudmesh.yaml
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-cloud/master/cloudmesh/etc/cloudmesh4.yaml
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-inventory/master/cloudmesh/inventory/etc/inventory.yaml
  - cms help

script: pytest -v tests/test_get.py

